# Generated by Django 5.2.3 on 2025-07-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_rename_birthdate_customer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='membership',
            field=models.CharField(choices=[('G', 'Gold'), ('B', 'Bronze'), ('S', 'Silver')], default='S', max_length=2),
        ),
    ]
