# Generated by Django 5.2.3 on 2025-07-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_rename_adress_address_alter_customer_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
